#!/bin/bash
# 🐉 Wyrm Auto-Deploy Script
# Automatically deploys Wyrm memory to all projects in a directory

# Don't exit on error - we handle errors ourselves
set +e

WYRM_VERSION="2.2.0"
DATE=$(date +%Y-%m-%d)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "██╗    ██╗██╗   ██╗██████╗ ███╗   ███╗"
echo "██║    ██║╚██╗ ██╔╝██╔══██╗████╗ ████║"
echo "██║ █╗ ██║ ╚████╔╝ ██████╔╝██╔████╔██║"
echo "██║███╗██║  ╚██╔╝  ██╔══██╗██║╚██╔╝██║"
echo "╚███╔███╔╝   ██║   ██║  ██║██║ ╚═╝ ██║"
echo " ╚══╝╚══╝    ╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝"
echo -e "    Auto-Deploy v${WYRM_VERSION}${NC}"
echo ""

# Get target directory
TARGET_DIR="${1:-.}"
TARGET_DIR=$(realpath "$TARGET_DIR")

echo -e "${YELLOW}🔍 Scanning: ${TARGET_DIR}${NC}"
echo ""

# Function to detect project type
detect_project_type() {
    local dir="$1"
    
    if [[ -f "$dir/package.json" ]]; then
        if grep -q '"next"' "$dir/package.json" 2>/dev/null; then
            echo "nextjs"
        elif grep -q '"react"' "$dir/package.json" 2>/dev/null; then
            echo "react"
        elif grep -q '"vue"' "$dir/package.json" 2>/dev/null; then
            echo "vue"
        else
            echo "nodejs"
        fi
    elif [[ -f "$dir/requirements.txt" ]] || [[ -f "$dir/setup.py" ]] || [[ -f "$dir/pyproject.toml" ]]; then
        echo "python"
    elif [[ -f "$dir/composer.json" ]] || [[ -f "$dir/index.php" ]]; then
        echo "php"
    elif [[ -f "$dir/Cargo.toml" ]]; then
        echo "rust"
    elif [[ -f "$dir/go.mod" ]]; then
        echo "go"
    elif [[ -f "$dir/docker-compose.yml" ]] || [[ -f "$dir/Dockerfile" ]]; then
        echo "docker"
    elif [[ -f "$dir/Gemfile" ]]; then
        echo "ruby"
    else
        echo "unknown"
    fi
}

# Function to get stack string
get_stack_string() {
    local type="$1"
    case "$type" in
        nextjs) echo "Next.js, React, TypeScript" ;;
        react) echo "React, JavaScript/TypeScript" ;;
        vue) echo "Vue.js, JavaScript/TypeScript" ;;
        nodejs) echo "Node.js, JavaScript/TypeScript" ;;
        python) echo "Python 3.x" ;;
        php) echo "PHP 8.x" ;;
        rust) echo "Rust" ;;
        go) echo "Go" ;;
        docker) echo "Docker, Containers" ;;
        ruby) echo "Ruby" ;;
        *) echo "Unknown" ;;
    esac
}

# Function to get dev command
get_dev_command() {
    local type="$1"
    case "$type" in
        nextjs|react|vue|nodejs) echo "npm run dev" ;;
        python) echo "python main.py" ;;
        php) echo "php -S localhost:8000" ;;
        rust) echo "cargo run" ;;
        go) echo "go run ." ;;
        docker) echo "docker-compose up -d" ;;
        ruby) echo "bundle exec ruby main.rb" ;;
        *) echo "# Add dev command" ;;
    esac
}

# Function to create wyrm files
create_wyrm_files() {
    local dir="$1"
    local name=$(basename "$dir")
    local type=$(detect_project_type "$dir")
    local stack=$(get_stack_string "$type")
    local dev_cmd=$(get_dev_command "$type")
    
    mkdir -p "$dir/.wyrm"
    
    # Create hoard.md
    cat > "$dir/.wyrm/hoard.md" << EOF
# Wyrm Hoard // ${name}

> **Last Updated:** ${DATE}
> **Project:** ${name}
> **Type:** ${type}

## Project Overview

**Name:** ${name}  
**Type:** ${type^} project  
**Stack:** ${stack}  

## Current Status

### Completed
- [ ] Initial setup

### In Progress
- [ ] Development

## Architecture

### Key Files
| File | Purpose |
|------|---------|
| TODO | Add key files |

## Notes

- Auto-generated by Wyrm v${WYRM_VERSION}
- Update this file with project details
EOF

    # Create chronicles.md
    cat > "$dir/.wyrm/chronicles.md" << EOF
# Wyrm Chronicles // ${name}

> Session history for ${name}

---

## Session: ${DATE}

### Objectives
- Initial Wyrm setup

### Completed
1. Auto-deployed Wyrm memory

### Files Changed
- .wyrm/ folder created

---
EOF

    # Create quests.md
    cat > "$dir/.wyrm/quests.md" << EOF
# Wyrm Quests // ${name}

> Task list for ${name}

---

## High Priority

- [ ] **Setup**
  - Review project structure
  - Document architecture

## Medium Priority

- [ ] Add project-specific tasks

## Low Priority

- [ ] Future enhancements

## Completed

- [x] Wyrm initialization (${DATE})
EOF

    # Create protocol.md
    cat > "$dir/.wyrm/protocol.md" << EOF
# Wyrm Protocol // ${name}

> Guidelines for AI working on this project

## Session Start

Read these files first:
- .wyrm/hoard.md
- .wyrm/chronicles.md
- .wyrm/quests.md

Check status:
\`\`\`bash
git log --oneline -5
git status
\`\`\`

## Commands

\`\`\`bash
# Development
${dev_cmd}
\`\`\`

## Code Rules

- Follow project conventions
- Document changes
- Test before committing

## Session End

1. Update chronicles.md with what was done
2. Update quests.md (mark complete, add new)
3. Update hoard.md if architecture changed
4. Commit and push
EOF

    # Create .github/copilot-instructions.md for Copilot integration
    mkdir -p "$dir/.github"
    cat > "$dir/.github/copilot-instructions.md" << EOF
# Copilot Instructions

> Auto-generated by Wyrm. These instructions are loaded by GitHub Copilot Chat.

## Project Context

This project uses **Wyrm** for persistent AI memory. Before making changes:

1. Read \`.wyrm/hoard.md\` for project architecture
2. Read \`.wyrm/quests.md\` for pending tasks  
3. Read \`.wyrm/chronicles.md\` for recent session history

## Session Protocol

When working on this project:

1. **Start**: Check \`.wyrm/quests.md\` for current priorities
2. **During**: Reference \`.wyrm/hoard.md\` for architecture decisions
3. **End**: Update \`.wyrm/chronicles.md\` with what was done

## Code Standards

- Follow existing patterns in the codebase
- Check \`.wyrm/protocol.md\` for project-specific rules
- Document architectural changes in \`.wyrm/hoard.md\`

## Important Files

See \`.wyrm/hoard.md\` for the key files table.
EOF

    echo -e "${GREEN}✓${NC} ${name} (${type})"
}

# Function to create workspace hoard
create_workspace_hoard() {
    local dir="$1"
    local name=$(basename "$dir")
    
    mkdir -p "$dir/.wyrm"
    
    # Scan for projects
    local projects=""
    local project_table=""
    
    for subdir in "$dir"/*/; do
        if [[ -d "$subdir" ]] && [[ ! "$(basename "$subdir")" == .* ]]; then
            local subname=$(basename "$subdir")
            local subtype=$(detect_project_type "$subdir")
            local substack=$(get_stack_string "$subtype")
            local has_wyrm="❌"
            [[ -d "$subdir/.wyrm" ]] && has_wyrm="✅"
            project_table="${project_table}| **${subname}** | ${subtype^} | ${substack} | ${has_wyrm} |\n"
        fi
    done
    
    cat > "$dir/.wyrm/hoard.md" << EOF
# Wyrm Hoard // ${name} Workspace

> **Last Updated:** ${DATE}
> **Workspace:** ${name}

## Workspace Overview

Unified memory for all projects in this workspace.

## Projects

| Project | Type | Stack | Wyrm |
|---------|------|-------|------|
$(echo -e "$project_table")

## Quick Commands

\`\`\`bash
# Rescan and update this file
wyrm-deploy "${dir}"
\`\`\`

## Notes

- Auto-generated by Wyrm v${WYRM_VERSION}
- Run wyrm-deploy to update project list
EOF

    # Create chronicles.md
    cat > "$dir/.wyrm/chronicles.md" << EOF
# Wyrm Chronicles // ${name} Workspace

> Unified session history

---

## Session: ${DATE}

### Completed
1. Auto-deployed Wyrm to workspace
2. Scanned subdirectories

---
EOF

    # Create quests.md
    cat > "$dir/.wyrm/quests.md" << EOF
# Wyrm Quests // ${name} Workspace

> Unified task list across all projects

---

## High Priority

- [ ] Review all project hoards

## Completed

- [x] Wyrm workspace initialization (${DATE})
EOF

    # Create protocol.md
    cat > "$dir/.wyrm/protocol.md" << EOF
# Wyrm Protocol // ${name} Workspace

> Guidelines for AI working across projects

## Session Start

For **workspace-level** work:
- .wyrm/hoard.md (project overview)
- .wyrm/quests.md (unified tasks)

For **project-specific** work:
- {project}/.wyrm/hoard.md
- {project}/.wyrm/chronicles.md
- {project}/.wyrm/quests.md

## Switching Projects

1. Read the project's .wyrm/ folder
2. Check hoard.md for architecture
3. Check chronicles.md for recent changes
4. Check quests.md for pending tasks

## Session End

1. Update project-level chronicles.md
2. Update workspace chronicles.md if cross-project
3. Mark completed quests
EOF
}

# Count projects
total=0
created=0
skipped=0

# Process subdirectories
for subdir in "$TARGET_DIR"/*/; do
    if [[ -d "$subdir" ]] && [[ ! "$(basename "$subdir")" == .* ]]; then
        ((total++))
        name=$(basename "$subdir")
        
        if [[ -d "$subdir/.wyrm" ]]; then
            echo -e "${YELLOW}⊘${NC} ${name} (already has .wyrm)"
            ((skipped++))
        else
            create_wyrm_files "$subdir"
            ((created++))
        fi
    fi
done

echo ""

# Create workspace-level wyrm
if [[ ! -d "$TARGET_DIR/.wyrm" ]]; then
    echo -e "${CYAN}📁 Creating workspace-level .wyrm...${NC}"
    create_workspace_hoard "$TARGET_DIR"
    echo -e "${GREEN}✓${NC} Workspace memory created"
else
    echo -e "${YELLOW}⊘${NC} Workspace .wyrm already exists (updating...)"
    create_workspace_hoard "$TARGET_DIR"
    echo -e "${GREEN}✓${NC} Workspace memory updated"
fi

echo ""
echo -e "${GREEN}═══════════════════════════════════════${NC}"
echo -e "${GREEN}🐉 Wyrm deployment complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════${NC}"
echo ""
echo -e "   Projects scanned: ${total}"
echo -e "   Wyrm created:     ${GREEN}${created}${NC}"
echo -e "   Already existed:  ${YELLOW}${skipped}${NC}"
echo ""
echo -e "${CYAN}The dragon now remembers all.${NC}"
